################################################## 
# AMIWebServiceService_services_types.py 
# generated by ZSI.wsdl2python 
# 
# 
##################################################


import ZSI
from ZSI.TCcompound import Struct

############################## 
# targetNamespace 
#
# http://xml.apache.org/xml-soap 
##############################


# imported as: ns1
class xml_apache_org_xml_soap:
	targetNamespace = 'http://xml.apache.org/xml-soap'

	class mapItem_Def(ZSI.TCcompound.Struct):
		schema = 'http://xml.apache.org/xml-soap'
		type = 'mapItem'

		def __init__(self, name=None, ns=None, **kw):
			# internal vars
			self._key = None
			self._value = None

			TClist = [ZSI.TC.String(pname="key",aname="_key", optional=1), ZSI.TC.String(pname="value",aname="_value", optional=1), ]

			oname = name

			if name:
				aname = '_%s' % name
				if ns:
					oname += ' xmlns="%s"' % ns
				else:
					oname += ' xmlns="%s"' % self.__class__.schema
			else:
				aname = None

			ZSI.TCcompound.Struct.__init__(self, self.__class__, TClist,
						       pname=name, inorder=0,
						       aname=aname, oname=oname,
						       **kw)

	class Map_Def(ZSI.TCcompound.Struct):
		schema = 'http://xml.apache.org/xml-soap'
		type = 'Map'

		def __init__(self, name=None, ns=None, **kw):
			# internal vars
			self._item = None

			TClist = [ns1.mapItem_Def(name="item", ns=ns, repeatable=1, optional=1), ]

			oname = name

			if name:
				aname = '_%s' % name
				if ns:
					oname += ' xmlns="%s"' % ns
				else:
					oname += ' xmlns="%s"' % self.__class__.schema
			else:
				aname = None

			ZSI.TCcompound.Struct.__init__(self, self.__class__, TClist,
						       pname=name, inorder=0,
						       aname=aname, oname=oname,
						       hasextras=1, **kw)

# define class alias for subsequent ns classes
ns1 = xml_apache_org_xml_soap



############################## 
# targetNamespace 
#
# https://atlastagcollector.in2p3.fr:8443/AMI/services/AMIWebService 
##############################


# imported as: ns2
class https___atlastagcollector_in2p3_fr_8443_AMI_services_AMIWebService:
	targetNamespace = 'https://atlastagcollector.in2p3.fr:8443/AMI/services/AMIWebService'

	class ArrayOf_xsd_string_Def(ZSI.TCcompound.Array):
		def __init__(self, name = None, ns = None, **kw):
			ZSI.TCcompound.Array.__init__(self, 'arrayTypeNS:string[]', ZSI.TC.String(name=None,typed=0), pname=name, aname='_%s' % name, oname='%s xmlns:arrayTypeNS="http://www.w3.org/2001/XMLSchema"' % name, **kw)

# define class alias for subsequent ns classes
ns2 = https___atlastagcollector_in2p3_fr_8443_AMI_services_AMIWebService



