#!/usr/bin/env python
# this script is only used if pyAMI was not installed with distribute
# otherwise the 'entry_points' setup argument is used to call directly into
# pyAMI.ami. See the setup.py script.

from pyAMI.ami import ami
ami()
